version: '3'
# define all services
services: 
  db:
    container_name: db
    build: .docker/mysql/
    environment: 
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDb
    restart: always
    ports:
      - 3306:3306

  web:
    container_name: web
    build: .docker/web/
    environment: 
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    ports:
      - 80:80
    depends_on:
      - db # start mysql before apache
    volumes: 
      - .:/var/www/html # put the contents of the apache/html in the container var/www/html

